---
deployment:
    tasks:
    - export DEPLOYPATH=/home/ikerzerb/repositorio/Probaxx
    - rm -RF $DEPLOYPATH/*
    - cp -RF model $DEPLOYPATH
    - cp -RF view $DEPLOYPATH
    - cp -RF controller $DEPLOYPATH